version: '3.8'

services:
  website:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: laravel-website
    restart: always
    working_dir: /var/www/
    volumes:
      - ../code:/var/www
  
  webserver:
    image: nginx:1.22-alpine
    container_name: laravel-nginx
    restart: always
    ports:
      - "9000:80"
    volumes:
      - ../code:/var/www
      - ./conf:/etc/nginx/conf.d  